# Generated by Django 6.1.1 on 2026-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='معرف الفاتورة في NOWPayments', max_length=100, unique=True)),
                ('payment_status', models.CharField(default='waiting', help_text='حالة الدفع: waiting, confirming, confirmed, failed, etc.', max_length=50)),
                ('pay_address', models.CharField(help_text='عنوان المحفظة التي سيحول عليها العميل', max_length=255)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='المبلغ بالقيمة المطلوبة (USD مثلاً)', max_digits=12)),
                ('price_currency', models.CharField(default='usd', help_text='عملة التسعير الأساسية', max_length=10)),
                ('pay_currency', models.CharField(help_text='العملة الرقمية المختارة للدفع مثل btc, usdt', max_length=10)),
                ('pay_amount', models.DecimalField(decimal_places=8, help_text='المبلغ المطلوب بالعملة الرقمية', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
