# Generated by Django 6.1.1 on 2026-09-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Subscriber Email')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='Is Subscribed?')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('image', models.ImageField(upload_to='marketing/banners/', verbose_name='Banner Image')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='Target URL')),
                ('position', models.CharField(choices=[('hero', 'Homepage Hero Slider'), ('sidebar', 'Sidebar Banner'), ('footer', 'Footer Banner')], default='hero', max_length=30, verbose_name='Display Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Promotion Banner',
                'verbose_name_plural': 'Promotion Banners',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Purchase Amount')),
                ('usage_limit', models.PositiveIntegerField(default=100, verbose_name='Total Usage Limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='Catalog.category', verbose_name='Applicable Categories')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='Catalog.product', verbose_name='Applicable Products')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
