# Generated by Django 6.1.1 on 2026-09-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='رقم الطلب المرتبط')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الضريبة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة'), ('refunded', 'مسترجعة')], default='pending', max_length=20, verbose_name='حالة الفاتورة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'الدفع عند الاستلام')], max_length=50, verbose_name='بوابة الدفع')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='معرف المعاملة (Gateway Tx ID)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('success', 'ناجحة'), ('failed', 'فاشلة'), ('pending', 'معلقة')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المعاملة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Accountant.invoice', verbose_name='الفاتورة المرتبطة')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ المستحقات')),
                ('commission_deducted', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='عمولة المنصة المخصومة')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الصافي المحول للبائع')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('approved', 'تمت الموافقة'), ('paid', 'تم التحويل')], default='pending', max_length=20, verbose_name='حالة التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل الفعلي')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب المسؤول')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
        ),
    ]
